title: Blog
email: mathieu.tarral@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, interested in operating systems, hypervisors, malwares
  and security research
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mtarral
github_username:  Wenzel

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
