title: Blog
email: mathieu.tarral@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, interested in hypervisors, malwares
  and security research.
  Bringing Virtual Machine Introspection for QEMU/KVM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mtarral
github_username:  Wenzel

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
